---
- hosts: localhost
  connection: local
  become: yes

  # NOTE: Tired of relying on outside roles.
  # test.yaml playbook assumes that Java was previously
  # installed on the CI Docker image

  tasks:
    - include: tasks/main.yaml
  handlers:
    - include: handlers/main.yaml
  vars_files:
    - defaults/main.yaml
