---
- hosts: localhost
  connection: local
  become: yes

  # NOTE: Tired of relying on outside roles.
  # Assumes that Java was previously 
  # installed on the CI Docker image

  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
  vars_files:
    - defaults/main.yml
