---
- hosts: localhost
  connection: local
  become: yes

  roles:
    # - ansiblebit.oracle-java
    - geerlingguy.java

  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  vars_files:
  - defaults/main.yml
