---
- name: Installation | Create configuration directory
  ansible.builtin.file:
    path: "{{ conf_dest }}"
    state: directory
    mode: 0755
    force: yes

  tags:
    - installation

- name: Installation | Change configuration directory ownership
  ansible.builtin.file:
    path: "{{ conf_dest }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    force: yes
  when: kafka_system_users.enabled

  tags:
    - installation
