---
- name: System Users | Create user group
  group:
    name: "{{ kafka_system_users.group }}"
    state: present

- name: System Users | Check if sudoers file exists
  stat:
    path: /etc/sudoers
  register: sudoers_status

- name: System Users | Include to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: "^%wheel" # or defaults to EOF
    line: "^%{{ kafka_system_users.group }} ALL=(ALL) NOPASSWD: ALL"
  when: sudoers_status.stat.exists

- name: System Users | Create an user for each service
  user:
    name: "{{ item }}"
    groups:
      - "{{ kafka_system_users.group }}"
    system: yes
    create_home: no
    append: yes
  with_items: "{{ confluent_services }}"
