---
- name: Logs | Create a dir for each service
  file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: 0644
  with_items: "{{ confluent_services }}"
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change log dir ownership
  file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
  with_items: "{{ confluent_services }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Logs | Create symlink from Confluent directory
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - src: "{{ dst_path }}/confluent-{{ confluent_version }}/logs/"
      dest: "{{ log_basepath }}/confluent"
  tags:
    - service
    - logs
    - configuration
