---
- name: Logs | Create a dir for each service
  file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: 0644
  with_items: "{{ confluent_services }}"
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change log dir ownership
  file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
  with_items: "{{ confluent_services }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Log4J | Create config files
  template:
    src: "log4j.properties.j2"
    dest: "{{ conf_dest }}/log4j.properties"
    mode: 0644
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change Log4j config files ownership
  file:
    path: "{{ conf_dest }}/log4j.properties"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: "{{ kafka_system_users.permissions.file_mode }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Logs | Create symlink from Confluent directory
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - src: "{{ log4j_log_dir }}"
      dest: "{{ log_basepath }}/confluent"
  when: create_link_log_dir
  tags:
    - service
    - logs
    - configuration
