---
- name: Logs | Create a dir for each service
  ansible.builtin.file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: 0644
  loop: "{{ confluent_services }}"
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change log dir ownership
  ansible.builtin.file:
    path: "{{ log_basepath }}/{{ item }}"
    state: directory
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
  loop: "{{ confluent_services }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Log4J | Create config files
  ansible.builtin.template:
    src: "log4j.properties.j2"
    dest: "{{ conf_dest }}/log4j.properties"
    mode: 0644
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change Log4j config files ownership
  ansible.builtin.file:
    path: "{{ conf_dest }}/log4j.properties"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: "{{ kafka_system_users.permissions.file_mode }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Log4J | Create log directory
  ansible.builtin.file:
    path: "{{ log4j_log_dir }}"
    state: directory
    mode: 0644
  tags:
    - service
    - logs
    - configuration

- name: System Users | Change log4j directory ownership
  ansible.builtin.file:
    path: "{{ log4j_log_dir }}"
    state: directory
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
  when: kafka_system_users.enabled
  tags:
    - service
    - logs
    - configuration

- name: Logs | Create symlink from Confluent directory
  ansible.builtin.file:
    src: "{{ log4j_log_dir }}"
    dest: "{{ log_basepath }}/confluent"
    state: link
    force: true

  when: create_link_log_dir
  tags:
    - service
    - logs
    - configuration
