---

- name: RHEL | Enable epel-release
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - installation

- block: # Try to install SELinux bindings with Pip
    - name: SELinux | Install Python bindings
      pip:
        name: selinux
      tags:
        - installation

  rescue:
    - name: SELinux | Set Python packages map
      set_fact:
        libselinux:
          2:
            RedHat: libselinux-python
            Debian: python-selinux
          3:
            RedHat: python3-selinux
            Debian: python3-selinux

    - name: SELinux | Install Python bindings using package manager
      package:
        name: "{{ libselinux.get(ansible_python.version.major).get(ansible_os_family) }}"
        state: present
      when:
        - libselinux.get(ansible_python.version.major) is defined
        - libselinux.get(ansible_python.version.major).get(ansible_os_family) is defined
      tags:
        - installation
