---
- name: "TLS | Create secrets {{ ssl.path }}"
  file:
    path: "{{ ssl.path }}"
    state: directory

- name: "System Users | Change {{ ssl.path }} ownership"
  file:
    path: "{{ ssl.path }}"
    state: directory
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: 0600
  when: kafka_system_users.enabled

- name: TLS | Copy certs and keys from Ansible Vault
  copy:
    src: "{{ local.files }}/{{ item }}"
    dest: "{{ ssl.path }}"
  with_items: "{{ jkstores }}"

- name: System Users | Change certs and keys ownership
  file:
    path: "{{ ssl.path }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: 0600
  with_items: "{{ jkstores }}"
  when: kafka_system_users.enabled

- name: "TLS | Register new {{ service }} template with security layer"
  template:
    src: "{{ item }}.j2"
    dest: "{{ conf_dest }}/{{ item }}"
    force: yes
  with_items: "{{ templates }}"
  notify: restart {{ service }}

- name: System Users | Change services ownership
  file:
    path: "{{ conf_dest }}/{{ item }}"
    owner: "{{ confluent_services | first }}"
    group: "{{ kafka_system_users.group }}"
    mode: 0644
  with_items: "{{ templates }}"
  when: kafka_system_users.enabled
