---
version: 2

defaults: &defaults
  steps:
    - checkout
    - run: |
        pip install ansible==2.5.15

        # ansible-galaxy install -r requirements.yml
        ansible-galaxy install macunha1.confluent-kafka

        # Check code style and syntax
        ansible-playbook -c local --syntax-check test.yml
        # Install using test.yml playbook
        ansible-playbook -c local test.yml

jobs:
  test-alpine3:
    docker:
      - image: macunha1/ansible:alpine-3.11.5
    <<: *defaults
  test-centos6:
    docker:
      - image: macunha1/ansible:centos-6
    <<: *defaults
  test-centos7:
    docker:
      - image: macunha1/ansible:centos-7
    <<: *defaults
  test-debian9:
    docker:
      - image: macunha1/ansible:debian-9
    <<: *defaults
  test-debian10:
    docker:
      - image: macunha1/ansible:debian-10
    <<: *defaults
  test-fedora27:
    docker:
      - image: ansible/ansible:fedora27
    <<: *defaults
  test-ubuntu16:
    docker:
      - image: macunha1/ansible:ubuntu-16.04
    <<: *defaults
  test-ubuntu20:
    docker:
      - image: macunha1/ansible:ubuntu-20.04
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      # Alpine issue: https://github.com/ansible/ansible/issues/23944
      # - test-alpine3
      # - test-centos6
      - test-centos7
      - test-debian9
      - test-debian10
      # - test-fedora27
      - test-ubuntu16
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      # - test-alpine3
      - test-centos7
      - test-debian9
      - test-debian10
      # - test-fedora27
      - test-ubuntu16
