---
version: 2

defaults: &defaults
  steps:
    - checkout
    - run: |
        pip install ansible==2.9.6

        # ansible-galaxy install -r requirements.yml
        ansible-galaxy install macunha1.confluent-kafka

        # Check code style and syntax
        ansible-playbook -c local --syntax-check test.yml
        # Install using test.yml playbook
        ansible-playbook -c local test.yml

jobs:
  test-alpine3:
    docker:
      - image: macunha1/ansible:java-alpine-3.11.5
    <<: *defaults
  test-centos6:
    docker:
      - image: macunha1/ansible:centos-6
    <<: *defaults
  test-centos7:
    docker:
      - image: macunha1/ansible:centos-7
    <<: *defaults
  test-debian9:
    docker:
      - image: macunha1/ansible:java-debian-9
    <<: *defaults
  test-debian10:
    docker:
      - image: macunha1/ansible:java-debian-10
    <<: *defaults
  test-fedora27:
    docker:
      - image: ansible/ansible:fedora27
    <<: *defaults
  test-ubuntu16:
    docker:
      - image: macunha1/ansible:java-ubuntu-16.04
    <<: *defaults
  test-ubuntu20:
    docker:
      - image: macunha1/ansible:java-ubuntu-20.04
    <<: *defaults
  ansible-lint:
    docker:
      - image: macunha1/ansible:py3-alpine-3.11.5
    steps:
      - checkout
      - run: |
          pip install ansible-lint -qq
          ansible-lint .

workflows:
  version: 2
  build:
    jobs:
      - test-alpine3
      - test-centos7
      - test-ubuntu20
      - ansible-lint
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-alpine3
      - test-centos7
      - test-debian9
      - test-debian10
      - test-ubuntu16
      - test-ubuntu20
