version: 2

defaults: &defaults
  steps:
    - checkout
    - run: |
        ansible-galaxy install -r requirements.yml
        ansible-galaxy install macunha1.confluent-kafka
        # Check code style and syntax
        ansible-playbook -c local --syntax-check test.yml
        # First run to install
        ansible-playbook -c local test.yml

jobs:
  test-centos6:
    docker:
      - image: macunha1/ansible:centos-6
    <<: *defaults
  test-centos7:
    docker:
      - image: williamyeh/ansible:centos7
    <<: *defaults
  test-debian8:
    docker:
      - image: williamyeh/ansible:debian8
    <<: *defaults
  test-debian9:
    docker:
      - image: williamyeh/ansible:debian9
    <<: *defaults
  test-ubuntu14:
    docker:
      - image: macunha1/ansible:ubuntu-14.04
    <<: *defaults
  test-ubuntu16:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    <<: *defaults
  test-alpine3:
    docker:
      - image: williamyeh/ansible:alpine3
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
    - test-centos7
    # - test-debian8 # Oracle Java in Debian 8 fails to install, breaks the build
    - test-debian9
    - test-ubuntu14
    - test-ubuntu16
    # - test-alpine3 # TODO: Implement generic linux vars for ansiblebit.oracle-java
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
    - test-centos7
    - test-debian9
    - test-ubuntu14
    - test-ubuntu16
