version: 2

defaults: &defaults
  steps:
    - checkout
    - run: |
        # ansible-galaxy install -r requirements.yml
        ansible-galaxy install geerlingguy.java
        ansible-galaxy install macunha1.confluent-kafka
        # Check code style and syntax
        ansible-playbook -c local --syntax-check test.yml
        # First run to install
        ansible-playbook -c local test.yml


jobs:
  test-centos7:
    docker:
      - image: williamyeh/ansible:centos7
    <<: *defaults
  test-debian8:
    docker:
      - image: williamyeh/ansible:debian8
    <<: *defaults
  test-debian9:
    docker:
      - image: williamyeh/ansible:debian9
    <<: *defaults
  test-ubuntu16:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    <<: *defaults
  test-ubuntu18:
    docker:
      - image: williamyeh/ansible:ubuntu18.04
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - test-centos7
      # Debian-based distros
      - test-debian8
      - test-debian9
      - test-ubuntu16
      # - test-ubuntu18 # TODO
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-centos7
      - test-debian8
      - test-debian9
      - test-ubuntu16
      # - test-ubuntu18 # TODO
