---
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: yes
    min-spaces-from-content: 1
  document-end: disable
  document-start: enable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: consistent
    check-multi-line-strings: no
  # key-duplicates: enable
  line-length:
    max: 120
    allow-non-breakable-words: yes
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  # trailing-spaces: disable
  truthy:
    allowed-values:
      - !!str yes
      - !!str no
    level: warning
