---
- name: Handlers | Flush
  meta: flush_handlers

- name: Handlers | Restart Kafka Service
  become: yes
  service:
    name: kafka
    state: "{{ item }}"
  with_items:
    - stopped
    - started
