---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: ${VAGRANT_DEFAULT_PROVIDER}

platforms:
  - &VAGRANT_PLATFORM
    name: debian
    box: debian/bullseye64
    memory: 4096
    cpus: ${VAGRANT_CPU_CORES:-2}

    groups:
      - zookeeper
      - kafka

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      ansible_pipelining: true

verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
