---
- name: Systemd | Create Init script for services
  ansible.builtin.template:
    src: service.j2
    dest: "{{ initscripts_path }}/{{ confluent_service.value.file_name }}"
    mode: 0751
    force: true
  become: true
  vars:
    service_name: "{{ confluent_service.key }}"
    daemon_start: "{{ confluent_service.value.daemon_start }}"
    daemon_opts: "{{ confluent_service.value.daemon_opts }}"
    daemon_stop: "{{ confluent_service.value.daemon_stop }}"
    daemon_status: "{{ confluent_service.value.daemon_status }}"

  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: confluent_service

- name: System Users | Change Init script ownership
  ansible.builtin.file:
    path: "{{ initscripts_path }}/{{ confluent_service.value.file_name }}"
    owner: "{{ confluent_service.value.user }}"
    group: "{{ kafka_system_users.group }}"
    force: true
  become: true

  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: confluent_service

  when: kafka_system_users.enabled

- name: System Users | Render environment file from template
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.path }}"
    mode: 0755
    force: true

  loop:
    - template: "kafka-env.sh.j2"
      path: "{{ kafka_envfile_path }}"
      group: "{{ groups['kafka'] }}"

    - template: "zookeeper-env.sh.j2"
      path: "{{ zookeeper_envfile_path }}"
      group: "{{ groups['zookeeper'] }}"

  when:
    - item.group is defined
    - inventory_hostname in item.group

- name: System Users | Change environment file ownership
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    group: "{{ kafka_system_users.group }}"
    force: true

  loop:
    - owner: "kafka"
      path: "{{ kafka_envfile_path }}"
      group: "{{ groups['kafka'] }}"

    - owner: "zookeeper"
      path: "{{ zookeeper_envfile_path }}"
      group: "{{ groups['zookeeper'] }}"

  when:
    - kafka_system_users.enabled
    - item.group is defined
    - inventory_hostname in item.group

- name: Systemd | Create services unit
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ confluent_service.key }}.service"
    mode: 0640
    force: true

  vars:
    service_name: "{{ confluent_service.key }}"
    file_name: "{{ confluent_service.value.file_name }}"

  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: confluent_service

  become: true

- name: System Users | Change service unit ownership
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ confluent_service.key }}.service"
    mode: 0640
    group: "{{ kafka_system_users.group }}"
    force: yes

  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: confluent_service

  when: kafka_system_users.enabled

- name: Systemd | Reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Systemd | Configure service
  ansible.builtin.systemd:
    name: "{{ confluent_service.key }}"
    state: "{{ confluent_service.value.state | default('started') }}"
    enabled: "{{ confluent_service.value.enabled | default(true) }}"

  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: confluent_service

  register: result
  until: result is succeeded
  retries: 3
  ignore_errors: yes
