---
- name: Systemd | Create Init script for services
  template:
    src: service.j2
    dest: "{{ initscripts_path }}/{{ item.value.file_name }}"
    mode: 0751
    force: yes
  become: yes
  with_dict: "{{ services }}"

- name: System Users | Change Init script ownership
  file:
    path: "{{ initscripts_path }}/{{ item.value.file_name }}"
    owner: "{{ item.value.user }}"
    group: "{{ kafka_system_users.group }}"
    force: yes
  become: yes
  with_dict: "{{ services }}"
  when: kafka_system_users.enabled

- name: System Users | Render environment file from template
  template:
    src: "{{ item.template }}"
    dest: "{{ confluent_kafka_env_file_path }}/{{ item.name }}"
    mode: 0755
    force: yes
  when:
    - item.group is defined
    - inventory_hostname in item.group
  with_items:
    - template: "kafka-env.sh.j2"
      name: "kafka-env.sh"
      group: "{{ groups['kafka'] }}"
    - template: "zookeeper-env.sh.j2"
      name: "zookeeper-env.sh"
      group: "{{ groups['zookeeper'] }}"

- name: System Users | Change environment file ownership
  file:
    path: "{{ confluent_kafka_env_file_path }}/{{ item.name }}"
    owner: "{{ item.owner }}"
    mode: "{{ kafka_system_users.permissions.directory_mode }}"
    group: "{{ kafka_system_users.group }}"
    force: yes
  when:
    - kafka_system_users.enabled
    - item.group is defined
    - inventory_hostname in item.group
  with_items:
    - owner: "kafka"
      name: "kafka-env.sh"
      group: "{{ groups['kafka'] }}"
    - owner: "zookeeper"
      name: "zookeeper-env.sh"
      group: "{{ groups['zookeeper'] }}"

- name: Systemd | Create services unit
  become: yes
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ item.value.file_name }}.service"
    mode: 0640
    force: yes
  with_dict: "{{ services }}"

- name: System Users | Change service unit ownership
  file:
    path: "/etc/systemd/system/{{ item.value.file_name }}.service"
    mode: 0640
    group: "{{ kafka_system_users.group }}"
    force: yes
  with_dict: "{{ services }}"
  when: kafka_system_users.enabled

- name: Systemd | Reload daemon
  systemd:
    daemon_reload: yes

- name: Systemd | Configure service
  systemd:
    name: "{{ item.value.file_name }}"
    state: "{{ item.value.state | default('started') }}"
    enabled: "{{ item.value.enabled | default(true) }}"
  with_dict: "{{ services }}"
  register: result
  until: result is succeeded
  retries: 3
  ignore_errors: yes
