---
- name: Init Script | Create scripts for services
  template:
    src: service.j2
    dest: "{{ initscripts_path }}/{{ item.value.file_name }}"
    mode: 0751
    force: yes
  become: yes
  with_dict: "{{ services }}"
  register: initscript_creation

- name: System Users | Change Init script ownership
  file:
    path: "{{ initscripts_path }}/{{ item.value.file_name }}"
    owner: "{{ item.value.user }}"
    group: "{{ kafka_system_users.group }}"
  become: yes
  with_dict: "{{ services }}"
  when: kafka_system_users.enabled

- name: Init Script | Link to initscripts path
  file:
    src: "{{ initscripts_path }}/{{ item.value.file_name }}"
    dest: "/etc/init.d/{{ item.value.file_name }}"
    owner: "{{ item.value.user }}"
    state: link
    force: yes
  with_dict: "{{ services }}"
  when:
    - initscripts_path not in [ "/etc/init.d", "/etc/init.d/" ]
    - initscript_creation.changed

- name: Init Script | Configure services
  service:
    name: "{{ item.value.file_name }}"
    state: "{{ item.value.state | default('started') }}"
    enabled: "{{ item.value.enabled | default(true) }}"
  with_dict: "{{ services }}"
