- name: Init Script | Create scripts for services
  template:
    src: service.j2
    dest: "{{ initscripts_path }}/{{ item.value.file_name }}"
    mode: 0751
  with_dict: "{{ services }}"
  become: yes
  register: initscript_creation

- name: System Users | Change Init script ownership
  file:
    path: "{{ initscripts_path }}/{{ item.value.file_name }}"
    owner: kafka
    group: "{{ kafka_system_users.group }}"
    force: yes
  become: yes
  when: kafka_system_users.enabled

- name: Init Script | Link to initscripts path
  file:
    src: "{{ initscripts_path }}/{{ item.value.file_name }}"
    dest: "/etc/init.d/{{ item.value.file_name }}"
    owner: "{{ item.value.user }}"
    state: link
    force: yes
  with_dict: "{{ services }}"
  when:
    - initscripts_path not in [ "/etc/init.d", "/etc/init.d/" ]
    - initscript_creation.changed

- name: Init Script | Start services
  service:
    name: "{{ item.value.file_name }}"
    state: started
  with_dict: "{{ services }}"
