---
name: Continuous Integration

"on":
  push:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Python | Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"

      - name: Python | Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Lint | Check Ansible and YAML
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint ansible ansible-lint

          yamllint -c .github/actions/config/yamllint.yaml .
          ansible-lint -c .github/actions/config/ansible.yaml .

  test:
    runs-on: self-hosted
    needs: build
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Python | Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"

      - name: Python | Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Test | Run Molecule
        run: |
          python -m pip install ansible \
            molecule molecule-vagrant \
            pytest testinfra

          mkdir -p ~/.ansible/roles/
          ln -s ${GITHUB_WORKSPACE} \
            ~/.ansible/roles/macunha1.confluent_kafka

          molecule test
        env:
          VAGRANT_DEFAULT_PROVIDER: libvirt

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    needs: test
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Python | Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"

      - name: Python | Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Galaxy | Import
        run: |
          python -m pip install ansible

          ansible-galaxy role import \
            --api-key ${ANSIBLE_GALAXY_API_KEY} \
            --branch main \
            macunha1 confluent_kafka
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
