---
name: Continuous Integration

"on":
  push:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible-image:
          - macunha1/ansible:centos-7
          # TODO: Make the CI work on those images again.
          # - macunha1/ansible:java-alpine-3.11.5
          # - macunha1/ansible:java-debian-10

    steps:
      - uses: actions/checkout@v2

      - name: Test | Run Playbook
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.ansible-image }}
          shell: bash
          options: -v ${{ github.workspace }}:/workspace
          run: |
            pip install ansible==2.9.6

            # NOTE: No longer installing the requirements.yaml in the test phase
            # to avoid (constant) issues with Java Hotspot 8. The Docker image
            # includes OpenJDK 8/11 by default, so tests won't rely on external
            # resources.
            # ansible-galaxy install -r requirements.yaml
            ansible-galaxy install macunha1.confluent_kafka

            # Check code style and syntax
            ansible-playbook -c local \
              --syntax-check /workspace/test.yaml

            # Install using test.yaml playbook
            ansible-playbook -c local /workspace/test.yaml

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Python | Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Lint | Check Ansible and YAML
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint ansible ansible-lint

          yamllint -c .github/actions/config/yamllint.yaml .
          ansible-lint -c .github/actions/config/ansible.yaml .

      - name: Galaxy | Import
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ansible-galaxy role import \
            --api-key ${ANSIBLE_GALAXY_API_KEY} \
            --branch main \
            macunha1 confluent_kafka
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
