---
name: Continuous Integration

"on":
  push:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Python | Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"

      - name: Python | Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Lint | Check Ansible and YAML
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint ansible ansible-lint

          yamllint -c .github/actions/config/yamllint.yaml .
          ansible-lint -c .github/actions/config/ansible.yaml .

  test:
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Workaround
        run: |
          mkdir -p ${{ github.workspace }}/molecule/default/roles/macunha1.confluent_kafka
          cp -R defaults/ handlers/ meta/ tasks/ templates/ \
            ${{ github.workspace }}/molecule/default/roles/macunha1.confluent_kafka

      - name: Test | Run Molecule
        uses: ucomesdag/molecule-action@main
        with:
          options: parallel

      - name: Test | Cache Container Images
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Cache failure isn't critical to the pipeline, move on
        continue-on-error: true

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    needs: test
    strategy:
      fail-fast: true

    steps:
      # NOTE: Anchors are not supported
      # Ref: https://github.com/macunha1/ansible-confluent-kafka/actions/runs/3304508364
      - name: Python | Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Galaxy | Import
        run: |
          python -m pip install ansible

          ansible-galaxy role import \
            --api-key ${ANSIBLE_GALAXY_API_KEY} \
            --branch main \
            macunha1 confluent_kafka
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
